server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform:
    hibernate:
      ddl-auto: update
  application:
    name: PRODUCT-SERVICE
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:9232}

 # cloud:
 #  config:
 #     import-check:
 #       enabled: false


#eureka:
#  instance:
#    prefere-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    servie-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http:localhost:8761/eureka}

